spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: simple-quote
                  uri: 'lb://SIMPLE-QUOTE'
                  predicates:
                      - Path=/simple-quote/**
                  filters:
                      - StripPrefix=1
                - id: ponctual-quote
                  uri: 'lb://PONCTUAL-QUOTE'
                  predicates:
                      - Path=/ponctual-quote/**
                  filters:
                      - StripPrefix=1
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
    port: 9999
management:
    endpoint:
        gateway:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
