services:

  active_mq:
    image: apache/activemq-artemis:latest-alpine
    container_name: rabbitmq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ARTEMIS_USER=mq
      - ARTEMIS_PASSWORD=mq


